#%RAML 1.0
title: Constraints description
version: 1.0
mediaType: application/json

types:
  rangeType:
    type: object
    properties:
      min: number
      max: number

  enumType:
    type: string[]

  constraint:
    type: object
    properties:
      domain:
        description: Constraint category. Can be ['Licensing','Access'] or name of service (for example 'PolicyManager' or 'VaultManager')
        type: string
      target:
        description: Dot-lined path to target field (or unique constraint name)
        type: string
      type:
        description: Constraint type ('enum'/'range'/'number'/'string')
        type: string
      value:
        description:
        type: enumType | rangeType | number | string

  constraints:
    type: array
    items: constraint
    minItems: 0
