#%RAML 1.0 Library

types:
  cursor:
    description: Specific location in some collection.
    type: string
  cursors:
    description: Cursors before and after the current page.
    type: object
    properties:
      before?: cursor
      after?: cursor
  paging:
    description: Paging format.
    type: object
    properties:
      cursors: cursors
