#%RAML 1.0 Library

types:
  debugInfo:
    description: Error debug information (map type)
    type: object
  kbLinkInfo:
    description: Components for kblink
    type: object
    properties:
      lineTag: string
      serCode: string
      version: string
      build: string
      product: string
      os: string
  error:
    description: Base error object
    type: object
    properties:
      domain:
        description: Error type or category. Can be ['Licensing','Access'] or name of service (for example 'PolicyManager' or 'VaultManager')
        type: string
      code:
        description: Error id or code, unique in the domain. Same as in 'reason' field
        type: string
      reason?:
        description: Obsolete. Error id or code, unique in the domain. Same as in 'code' field
        type: string
      context?:
        description: Error context dictionary
        type: object
      kbLink?: kbLinkInfo
      debug?: debugInfo
