#%RAML 1.0
title: Issue description
version: 1.0
mediaType: application/json

uses:
  error: error.raml

types:
  issue:
    type: object
    properties:
      link?:
        description: Link name or id, the constraint must be applied to
        type: string
      domain?:
        description: Type of reason the constraint is originated from
        type: string
        enum: [ "Access", "Licensing" ]
      target:
        description: Path to or id of sub-resource, which the issue concerns. May be required for composite resources
        type: string
      severity:
        description: Degree of trouble brought by the issue
        type: string
      error: error.error
  issues:
    type: array
    items: issue
    minItems: 0
