#%RAML 1.0
title: Tenant type definition
version: 1.0
mediaType: application/json

types:
  tenant:
    type: object
    properties:
      tenantId: string
      tenantName?: string
      tenantLocator: string

traits:
  tenancyScoped:
    headers:
      X-Apigw-Tenant-Id:
        type: string
        description: Tenant ID
      X-Apigw-Tenant-Locator:
        type: string
        description: Tenant Locator
    responses:
      403:
        description: Tenant scope in headers is not provided or access is denied
        body:
          type: string
