#%RAML 1.0 Library

uses:
  error: !include ../schemas/error.raml

types:
  ReasonUnableToUnlicense:
    description: 'Unable to unlicense'
    type: error.error
    properties:
      domain:
        type: string
        enum:
          - Licensing
        required: true
      reason:
        type: string
        enum:
          - ReasonUnableToUnlicense
        required: false
      code:
        type: string
        enum:
          - ReasonUnableToUnlicense
        required: true
