#%RAML 1.0 Library

uses:
  error: !include ../schemas/error.raml

types:
  ReasonUsageItemGoneRace:
    description: 'Usage item gone(race?)'
    type: error.error
    properties:
      domain:
        type: string
        enum:
          - Licensing
        required: true
      reason:
        type: string
        enum:
          - ReasonUsageItemGoneRace
        required: false
      code:
        type: string
        enum:
          - ReasonUsageItemGoneRace
        required: true
