#%RAML 1.0 Library

uses:
  error: !include ../schemas/error.raml

types:
  ReasonUsageItemNotFound:
    description: 'Usage item {{usage_item_id}} not found'
    type: error.error
    properties:
      domain:
        type: string
        enum:
          - Licensing
        required: true
      reason:
        type: string
        enum:
          - ReasonUsageItemNotFound
        required: false
      code:
        type: string
        enum:
          - ReasonUsageItemNotFound
        required: true
      context:
        type: object
        properties:
          usage_item_id:
            type: string
            required: true
        required: true
