#%RAML 1.0 Library

usage: Base types for alerts management
uses:
  common: ../libraries/common.raml

annotationTypes:
  order:
    description: Annotation describes order of enum values

types:
  Severity:
    type: string
    enum: [ok, warning, error, critical]
    (order): ok < warning < error < critical

  Type:
    description: Type of alert, has imposed severity and context keys
    properties:
      id: string
      enabled:
        type: boolean
        description: alerts of disabled types are treated as non-existent for any GET request until type is enabled again
        default: true
      severity: Severity
      context:
        type: string[]
        description: |
          Array of context keys. Using for completeness and
          correctness validation of alert context object
      searchableDetails:
        type: string[]
        description: |
          Keys indicate special parameters of details. By those parameters
          alerts of current type could be searched and filtered. Value of such
          parameters must have string type

  Context:
    type: object
    description: |
      Value of unique key for alerts with current type.
      Parameters of object are can be only strings.
      Variative structure of context is specified with custom types

  AlertBody:
    description: Body contains data needed to raise alert in listed context
    properties:
      id?: common.uuid
      type: string
      context: Context
      createdAt?:
        type: datetime
        format: rfc3339
      details?:
        type: object
        description: |
          Uninterpreted information about event.
          Variative structure of details is specified with custom types
      _source?:
        type: string
        description: Identifier of alert producer
      _sourceTimeStamp?:
        type: integer
        format: int64

  Alert:
    type: object
    description: Internal type for inheritance by custom alert structures
    properties:
      severity: Severity

  AlertView:
    type: Alert
    description: View of alert in responses
    properties:
      id: common.uuid
      type: string
      createdAt:
        type: datetime
        format: rfc3339
      deletedAt?:
        type: datetime
        format: rfc3339
        description: Null if current alert is active
      details:
        type: object
        description: |
          Copy of context is merged to details.
          Null if details and context is empty
      receivedAt:
        type: datetime
        format: rfc3339
      _source?:
        type: string
        description: Identifier of alert producer
      _sourceTimeStamp?:
        type: integer
        format: int64
      tenant:
        type: object
        properties:
          id:
            type: string
            description: Identifier of alert owner
          locator:
            type: string
            description: Ascending hierarchy of tenant ids separated by '/'
            example: /1/2/3/
      updatedAt:
        type: datetime
        format: rfc3339

  AlertID:
    properties:
      id: common.uuid

  AlertSync:
    properties:
      id: common.uuid
      _sourceTimeStamp:
        type: integer
        format: int64
        required: false