#%RAML 1.0 Library

usage: Schema of count response

traits:
  EmbedsForCountReport:
    queryParameters:
      embed_types:
        type: boolean
        description: Embed counts per type
      embed_severities:
        type: boolean
        description: Embed counts per severity
      embed_tenants:
        type: boolean
        description: |
          Embed counts per tenant. Can include embed_types and embed_severities

types:
  TypesEmbed:
    type: object
    description: |
      Count alerts per type. Keys of object are identifiers of alert
      types, values are counts of alerts of these types

  SeveritiesEmbed:
    type: object
    description: Count alerts per severity
    properties:
      critical: integer
      error: integer
      warning: integer

  CountResult:
    type: object
    description: Composite report about count of alerts
    properties:
      total: integer
      types:
        type: TypesEmbed
        required: false
      severities:
        type: SeveritiesEmbed
        required: false

  TenantCountResult:
    type: CountResult
    description: Count report for tenant
    properties:
      id:
        type: string
        description: Identifier of tenant
      locator:
        type: string
        description: Locator of tenant

  Report:
    type: CountResult
    description: Count report
    properties:
      tenants:
        type: TenantCountResult[]
        description: CountReport for all founded tenants by locator
        required: false

    examples:
      default: {total: 2}
      embed_types: {total: 2, types: {SomeType1: 0, SomeType2: 2}}
      embed_severities: {total: 3, severities: {warning: 0, error: 2, critical: 1}}
      embed_tenants: {total: 3, tenants: [{total: 3, id: "2", locator: "/1/2/"}]}
      embed_tenants_types: {
        total: 2,
        types: {SomeType1: 2},
        tenants: [
          {total: 1, types: {SomeType1: 1}, id: "2", locator: "/1/2/"},
          {total: 1, types: {SomeType1: 1}, id: "3", locator: "/1/3/"},
        ]
      }
      embed_tenants_severities: {
        total: 2,
        severities: {critical: 0, error: 1, warning: 1},
        tenants: [
          {
            total: 1,
            severities: {critical: 0, error: 1, warning: 0},
            id: "2",
            locator: "/1/2/"
          },
          {
            total: 1,
            severities: {critical: 0, error: 0, warning: 1},
            id: "3",
            locator: "/1/3/"
          }
        ]
      }