#%RAML 1.0 Library

usage: Types described status by alerts

uses:
  alert: alert.raml

types:
  Status:
    type: object
    description: |
      Status of any scope calculating by alerts. Status is the last of the most
      critical alerts in current scope
    properties:
      id: string
      type: string
      severity: alert.Severity
      created_at:
        type: datetime
        format: rfc3339

  ScopeStatus:
    type: object
    description: Status of selected scope
    properties:
      scope:
        type: object
        description: |
          Value of scope. Contains from values of context or searchable details
      status: Status