#%RAML 1.0 Library

uses:
  paging: ../schemas/paging.raml

traits:
  pageable:
    queryParameters:
      limit?:
        type: integer
        description: Number of element in the page
      before?:
        type: paging.cursor
        description: Cursor before the current page
      after?:
        type: paging.cursor
        description: Cursor after the current page
